// src/app/components/QuizAnswers/index.tsx
import QuizAnswer from "@/app/components/QuizAnswer";
import styles from "@/app/components/QuizAnswers/index.module.css";

import { Question, QuizAnswersProps, QuizData } from "@/app/type";
import { useState } from "react";

// export default function Home(props: Question) {
export default function Home(props: QuizAnswersProps) {
  const { quiz } = props;
  const answers = quiz.answers;

  const [isSelected, setIsSelected] = useState<boolean>(false);
  const [judgeText, setJudgeText] = useState<string | null>(null);
  const [judgeClass, setJudgeClass] = useState<string>("");

  const buttonDisabled = () => {
    setIsSelected(true);
  };
  const showJudgeFunction = (quiz: Question) => {
    setJudgeText(quiz.judge);

    if (quiz.judge === "正解!!") {
      setJudgeClass("judge_correct");
    } else {
      setJudgeClass("judge_false");
    }
  };

  return (
    <>
      {answers.map((answer: string, index: number) => (
        <div key={index}>
          <div className={styles.answerBox}>
            <QuizAnswer buttonDisabled={buttonDisabled} showJudgeFunction={showJudgeFunction} isSelected={isSelected} answer={answer} quiz={quiz} />
          </div>
        </div>
      ))}
      <div className={`${styles.correctBox} ${judgeClass}`}>{judgeText}</div>
    </>
  );
}

// src/components/QuizAnswers.vue
<script setup>
import QuizAnswer from './QuizAnswer.vue'
import { ref } from 'vue'

const props = defineProps(['quiz'])
const isSelected = ref(false)
const judgeText = ref('')
const judgeClass = ref('')

const buttonDisabled = () => {
  isSelected.value = true
}
const showJudgeFunction = (quiz) => {
  judgeText.value = quiz.judge
  console.log(quiz)

  if (quiz.judge === '正解!!') {
    judgeClass.value = 'judge_correct'
  } else {
    judgeClass.value = 'judge_false'
  }
}
</script>
<template>
  <div v-for="answer in props.quiz.answers" :key="answer.id" class="answerBox">
    <QuizAnswer
      @buttonDisabled="buttonDisabled(quiz.id)"
      @showJudge="showJudgeFunction(quiz)"
      :isSelected="isSelected"
      :answer="answer"
      :quiz="quiz"
    />
  </div>
  <!-- <div class="correctBox ">{{ judgeText }}</div> -->
  <div :class="`correctBox ${judgeClass}`">{{ judgeText }}</div>
</template>
